### ISSUE TITLE
loosen faraday dependency?

### ISSUE THREAD

**Issue by jronallo** [iiif-prezi/osullivan#57]
I'd like to use osullivan but have run into a dependency issue that prevents me from using it. I have a long-lived Blacklight application that includes a version of https://github.com/cbeer/blacklight_oai_provider which depends on an older version of faraday. I'm wary of making updates to that portion of code and I see that the osullivan use of faraday is pretty minimal. Any chance that osullivan could have its dependency loosened to allow for older versions?

**Comment by jpstroop** [comment]
Jason,
I don't know of a reason why this wouldn't work. I'd say go ahead and give
it a shot and make a PR if it does.

You should probably clear the VCR cache to be sure.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by jronallo** [comment]
@jpstroop Yes, sorry for the premature issue. I probably should have done a little more work myself before submitting an issue at night out of frustration. This isn't osullivan's problem yet. I'll do more work and create a pull request or close this.

**Comment by jpstroop** [comment]
Cool, np.

-Js

Sent via mobile. Please excuse typos, brevity, etc.
