### ISSUE TITLE
Transfer repo to iiif-prezi/

### ISSUE THREAD

**Issue by azaroth42** [iiif-prezi/osullivan#62]
Or elsewhere.

**Comment by jcoyne** [comment]
<img src="https://cdn.meme.am/instances/53208445.jpg">

**Comment by jpstroop** [comment]
@jcoyne I'm happy to move it wherever, it just can't stay here.

**Comment by jcoyne** [comment]
hydra-labs seems a likely place

**Comment by azaroth42** [comment]
Someone pick somewhere...

**Comment by jpstroop** [comment]
I think I'd rather go w/ iiif-prezi; plenty of non-Hydra people using it.

**Comment by jcoyne** [comment]
@jpstroop as long as I can have access

**Comment by jpstroop** [comment]
Should have happened seamlessly.
