### ISSUE TITLE
using Faraday >0.15.* causes errors

### ISSUE THREAD

**Issue by ebenenglish** [iiif-prezi/osullivan#75]
After a recent update we ran into errors with Faraday `0.16.2`:
```
RuntimeError: Adapter should be set using the `adapter` method, not `use`
```
The `use` method is called from `IIIF::Presentation::ImageResource#get_info` :
```
def get_info(svc_id)
  conn = Faraday.new("#{svc_id}/info.json") do |c|
    c.use Faraday::Response::RaiseError
    c.use Faraday::Adapter::NetHttp
  end
  resp = conn.get # raises exceptions that indicate HTTP problems
  JSON.parse(resp.body)
end
```

**Comment by minusdavid** [comment]
I think that I had errors for newer versions of other dependencies too. 

I think this might be a dead project now, unfortunately. I haven't gotten any responses to issues for over a year now 👎

**Comment by jduss4** [comment]
Also encountered this issue. Thanks for the tip about the Faraday version!

**Comment by jcoyne** [comment]
I'm no longer seeing this problem with Faraday 2.
